apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: astartevoyageringresses.api.astarte-platform.org
spec:
  group: api.astarte-platform.org
  names:
    kind: AstarteVoyagerIngress
    listKind: AstarteVoyagerIngressList
    plural: astartevoyageringresses
    shortNames:
    - avi
    singular: astartevoyageringress
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AstarteVoyagerIngress is the Schema for the astartevoyageringresses
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AstarteVoyagerIngressSpec defines the desired state of AstarteVoyagerIngress
          properties:
            api:
              description: AstarteVoyagerIngressAPISpec defines the specification
                of the APIs
              properties:
                annotationsService:
                  additionalProperties:
                    type: string
                  type: object
                cors:
                  type: boolean
                deploy:
                  type: boolean
                exposeHousekeeping:
                  type: boolean
                loadBalancerIp:
                  type: string
                nodeSelector:
                  type: string
                replicas:
                  format: int32
                  type: integer
                tlsRef:
                  description: LocalTypedReference contains enough information to
                    let you inspect or modify the referred object.
                  properties:
                    apiVersion:
                      description: API version of the referent.
                      type: string
                    kind:
                      description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                  type: object
                tlsSecret:
                  type: string
                type:
                  type: string
              type: object
            astarte:
              type: string
            broker:
              description: AstarteVoyagerIngressBrokerSpec defines the specification
                of the Broker
              properties:
                annotationsService:
                  additionalProperties:
                    type: string
                  type: object
                deploy:
                  type: boolean
                loadBalancerIp:
                  type: string
                maxConnections:
                  type: integer
                nodeSelector:
                  type: string
                replicas:
                  format: int32
                  type: integer
                tlsRef:
                  description: LocalTypedReference contains enough information to
                    let you inspect or modify the referred object.
                  properties:
                    apiVersion:
                      description: API version of the referent.
                      type: string
                    kind:
                      description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                  type: object
                tlsSecret:
                  type: string
                type:
                  type: string
              type: object
            dashboard:
              description: AstarteVoyagerIngressDashboardSpec defines the specification
                of the Dashboard
              properties:
                host:
                  type: string
                ssl:
                  type: boolean
                tlsRef:
                  description: LocalTypedReference contains enough information to
                    let you inspect or modify the referred object.
                  properties:
                    apiVersion:
                      description: API version of the referent.
                      type: string
                    kind:
                      description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                  type: object
                tlsSecret:
                  type: string
              type: object
            imagePullPolicy:
              description: PullPolicy describes a policy for if/when to pull a container
                image
              type: string
            letsencrypt:
              description: AstarteVoyagerIngressLetsEncryptSpec defines the specification
                of the Let's Encrypt Integration
              properties:
                acmeEmail:
                  type: string
                autoHTTPChallenge:
                  type: boolean
                challengeProvider:
                  properties:
                    dns:
                      properties:
                        credentialSecretName:
                          type: string
                        provider:
                          description: DNS Provider from the list https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md
                          type: string
                      type: object
                    http:
                      properties:
                        ingress:
                          description: LocalTypedReference contains enough information
                            to let you inspect or modify the referred object.
                          properties:
                            apiVersion:
                              description: API version of the referent.
                              type: string
                            kind:
                              description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                              type: string
                            name:
                              description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                              type: string
                          type: object
                      type: object
                  type: object
                domains:
                  items:
                    type: string
                  type: array
                staging:
                  type: boolean
                use:
                  type: boolean
              type: object
          required:
          - astarte
          type: object
        status:
          description: AstarteVoyagerIngressStatus defines the observed state of AstarteVoyagerIngress
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
