name: "Operator e2e tests"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testSuite:
        - "010"
        - "011"
        kubernetesNodeImage:
        - "kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55"
        - "kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62"
      fail-fast: false
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        # Ensure we're on Go 1.13
        go-version: '1.13.x'
    - uses: engineerd/setup-kind@v0.3.0
      with:
        version: "v0.7.0"
        image: "${{ matrix.kubernetesNodeImage }}"
    # Download Operator SDK binary
    - name: Download Operator SDK
      run: |
        curl -L -o operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.14.0/operator-sdk-v0.14.0-x86_64-linux-gnu
        chmod +x operator-sdk
    - name: Ensure KinD is up
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    - name: Setup needed resources
      run: |
        kubectl create namespace astarte-test
        kubectl apply -f deploy/service_account.yaml
        kubectl apply -f deploy/role.yaml
        kubectl apply -f deploy/role_binding.yaml
        kubectl create -f deploy/crds/api.astarte-platform.org_astartes_crd.yaml
        kubectl create -f deploy/crds/api.astarte-platform.org_astartevoyageringresses_crd.yaml
    - name: Run e2e tests
      run: ./operator-sdk test local ./test/e2e${{ matrix.testSuite }} --go-test-flags "-v -timeout 30m" --namespace astarte-test --up-local --no-setup
    - name: Dump debug info
      if: failure()
      run: |
        kubectl get pods -n astarte-test
        kubectl get deployment -n astarte-test
        kubectl get statefulset -n astarte-test
        kubectl get secrets -n astarte-test
        kubectl get configmaps -n astarte-test
        kubectl get pvc -n astarte-test
        kubectl describe astarte -n astarte-test || echo "Astarte already deleted"
    - name: Show pod states
      run: |
        kubectl get pods -n astarte-test
